# -*- coding: ISO-8859-15 -*-
# $Id$
"""Return custom document types."""

ooo_docbook_document_type = {
    'title': "portal_type_OOoDocbookDocument_title",
    'description': "portal_type_OOoDocbookDocument_description",
    'content_icon': 'ooo_docbook_document_icon.png',
    #'content_meta_type': 'CPS Document',
    'content_meta_type': 'OOoDocbookDocument',
    #'product': 'CPSDocument',
    'product': 'CPSOOo',
    #'factory': 'addCPSDocument',
    'factory': 'addOOoDocbookDocumentInstance',
    #'immediate_view': 'cpsdocument_edit_form',
    'immediate_view': 'cpsdocument_view',
    'global_allow': 1,
    'filter_content_types': 1,
    'allowed_content_types': [],
    'allow_discussion': 1,
    'cps_is_searchable': 1,
    # Choose between 'document', 'folder' or 'folderishdocument'
    # according to the need to store objects in your document or not.
    'cps_proxy_type': 'document',
    #'cps_proxy_type': 'folderishdocument',
    #'cps_proxy_type': 'folder',
    'schemas': ['metadata', 'common', 'ooo_docbook_document'],
    'layouts': ['common', 'ooo_docbook_document'],
    'flexible_layouts': [],
    'storage_methods': [],
    #'cps_workspace_wf': 'workspace_structured_document_wf',
    'cps_workspace_wf': 'workspace_content_wf',
    'cps_section_wf': 'section_content_wf',
    'use_content_status_history': True,
    'actions_add': ({'id': 'xml_docbook_export',
                     'name': 'action_xml_docbook_export',
                     'action': 'string:${object_url}/exportXmlDocbook',
                     'condition' : 'python:object.getContent().file',
                     'permissions': ('View',),
                     'category' : 'object',
                     'visible' : 1,
                     },
                    ),
    }


book_type = {
    'title': 'portal_type_Book_title',
    'description': 'portal_type_Book_description',
    'content_icon': 'book_icon.gif',
    'content_meta_type': 'CPS Document',
    'product': 'CPSDocument',
    'factory': 'addCPSDocument',
    'immediate_view': 'cpsdocument_view',
    'global_allow': 1,
    'filter_content_types': 1,
    'allowed_content_types': ('Page',),
    'allow_discussion': 0,
    'cps_is_searchable': 1,
    'cps_proxy_type': 'folderishdocument',
    'cps_display_as_document_in_listing': 0,
    'cps_is_portalbox': 0,
    'schemas': ('metadata', 'common', 'book'),
    'layouts': ('common', 'book'),
    'flexible_layouts': (),
    'storage_methods': (),
    'use_content_status_history': True,
    'actions': (
         {'id': 'view',
          'name': 'action_view',
          'action': 'string:${object_url}/book_view',
          'condition': '',
          'permission': ('View',),
          'category': 'object',
          'visible': 1,},
         {'id': 'new_content',
          'name': 'action_new_content',
          'action': 'string:${object_url}/folder_factories',
          'condition': "python:object.getTypeInfo().cps_proxy_type != 'document'",
          'permission': ('Modify portal content',),
          'category': 'object',
          'visible': 1,},
         {'id': 'contents',
          'name': 'action_folder_contents',
          'action': 'string:${object_url}/folder_contents',
          'condition': "python:object.getTypeInfo().cps_proxy_type != 'document'",
          'permission': ('Modify portal content',),
          'category': 'object',
          'visible': 1,},
         {'id': 'edit',
          'name': 'action_edit',
          'action': 'string:${object_url}/cpsdocument_edit_form',
          'condition': '',
          'permission': ('Modify portal content',),
          'category': 'object',
          'visible': 1,},
         {'id': 'metadata',
          'name': 'action_metadata',
          'action': 'string:${object_url}/cpsdocument_metadata',
          'condition': '',
          'permission': ('View',),
          'category': 'object',
          'visible': 1,},
         {'id': 'localroles',
          'name': 'action_local_roles',
          'action': 'string:${object_url}/folder_localrole_form',
          'condition': "python:object.getTypeInfo().cps_proxy_type != 'document'",
          'permission': ('Change permissions',),
          'category': 'object',
          'visible': 1,},
         {'id': 'status_history',
          'name': 'action_status_history',
          'action': 'string:${object_url}/content_status_history',
          'condition': '',
          'permission': ('View',),
          'category': 'workflow',
          'visible': 1,},
    )
}

chapter_type = {
    'title': 'portal_type_Chapter_title',
    'description': 'portal_type_Chapter_description',
    'content_icon': 'book_icon.gif',
    'content_meta_type': 'CPS Document',
    'product': 'CPSDocument',
    'factory': 'addCPSDocument',
    'immediate_view': 'cpsdocument_view',
    'global_allow': True,
    'filter_content_types': True,
    'allowed_content_types': ('Chapter', 'Page'),
    'allow_discussion': False,
    'cps_is_searchable': True,
    'cps_proxy_type': 'folderishdocument',
    'cps_display_as_document_in_listing': 1,
    'cps_is_portalbox': 0,
    'schemas': ('metadata', 'common', 'book'),
    'layouts': ('common', 'chapter'),
    'flexible_layouts': (),
    'storage_methods': (),
    'use_content_status_history': True,
    'actions': (
         {'id': 'view',
          'name': 'action_view',
          'action': 'string:${object_url}/book_view',
          'condition': '',
          'permission': ('View',),
          'category': 'object',
          'visible': 1,},
         {'id': 'new_content',
          'name': 'action_new_content',
          'action': 'string:${object_url}/folder_factories',
          'condition': "python:object.getTypeInfo().cps_proxy_type != 'document'",
          'permission': ('Modify portal content',),
          'category': 'object',
          'visible': 1,},
         {'id': 'contents',
          'name': 'action_folder_contents',
          'action': 'string:${object_url}/folder_contents',
          'condition': "python:object.getTypeInfo().cps_proxy_type != 'document'",
          'permission': ('Modify portal content',),
          'category': 'object',
          'visible': 1,},
         {'id': 'edit',
          'name': 'action_edit',
          'action': 'string:${object_url}/cpsdocument_edit_form',
          'condition': '',
          'permission': ('Modify portal content',),
          'category': 'object',
          'visible': 1,},
         {'id': 'metadata',
          'name': 'action_metadata',
          'action': 'string:${object_url}/cpsdocument_metadata',
          'condition': '',
          'permission': ('View',),
          'category': 'object',
          'visible': 1,},
         {'id': 'localroles',
          'name': 'action_local_roles',
          'action': 'string:${object_url}/folder_localrole_form',
          'condition': "python:object.getTypeInfo().cps_proxy_type != 'document'",
          'permission': ('Change permissions',),
          'category': 'object',
          'visible': 1,},
         {'id': 'status_history',
          'name': 'action_status_history',
          'action': 'string:${object_url}/content_status_history',
          'condition': '',
          'permission': ('View',),
          'category': 'workflow',
          'visible': 1,},
    )
}



def getDocumentTypes(portal=None):
    types = {}
    types['OOoDocbookDocument'] = ooo_docbook_document_type
    types['Book'] = book_type
    types['Chapter'] = chapter_type
    return types


ooo_docbook_document_schema = {
    'file': {
        'type': 'CPS OpenOffice.org Docbook Field',
        'data': {
                'default_expr': 'nothing',
                'is_searchabletext': 0,
                'suffix_text': '_text',
                'suffix_html': '_html',
                'suffix_html_subfiles': '_html_subfiles',
                'suffix_xml': '_xml',
                'suffix_xml_subfiles': '_xml_subfiles',
            },
        },
    'file_text': {
        'type': 'CPS String Field',
        'data': {
                'default_expr': 'string:',
                'is_searchabletext': 1,
            },
        },
    'file_xml': {
        'type': 'CPS File Field',
        'data': {
                'default_expr': 'nothing',
                'is_searchabletext': 0,
            },
        },
    'file_xml_subfiles': {
        'type': 'CPS SubObjects Field',
        'data': {
                'default_expr': 'nothing',
                'is_searchabletext': 0,
            },
        },
    'file_html': {
        'type': 'CPS File Field',
        'data': {
                'default_expr': 'nothing',
                'is_searchabletext': 0,
            },
        },
    'file_html_subfiles': {
        'type': 'CPS SubObjects Field',
        'data': {
                'default_expr': 'nothing',
                'is_searchabletext': 0,
            },
        },
    }


common_schema = {
    'allow_discussion': {
        'type': 'CPS Int Field',
        'data': {
            'default_expr': 'python:0',
            'is_searchabletext': 0,
            },
        },
    'preview': {
        'type': 'CPS Image Field',
        'data': {
            'default_expr': 'nothing',
            'is_searchabletext': 0,
            },
        },
    'delay': {
        'type': 'CPS Int Field',
        'data': {
            'default_expr': 'python:60',
            'is_searchabletext': 1,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': [],
            'write_ignore_storage': 0,
            'write_process_expr': '',
        },
    },
    'identifier': {
        'type': 'CPS String Field',
        'data': {
            'default_expr': 'string:',
            'is_searchabletext': 1,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': [],
            'write_ignore_storage': 0,
            'write_process_expr': '',
        },
    },
    'date_created': {
        'type': 'CPS DateTime Field',
        'data': {
            'default_expr': 'python:field.Date()',
            'is_searchabletext': 1,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': [],
            'write_ignore_storage': 0,
            'write_process_expr': '',
        },
    },
    'to_ministery': {
        'type': 'CPS String Field',
        'data': {
            'default_expr': 'string:Intérieur',
            'is_searchabletext': 1,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': [],
            'write_ignore_storage': 0,
            'write_process_expr': '',
        },
    },
    'mail_to': {
        'type': 'CPS String List Field',
        'data': {
            'default_expr': 'string:',
            'is_searchabletext': 1,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': [],
            'write_ignore_storage': 0,
            'write_process_expr': '',
        },
    },
    'date_valid': {
        'type': 'CPS Int Field',
        'data': {
            'default_expr': 'string:5',
            'is_searchabletext': 1,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': [],
            'write_ignore_storage': 0,
            'write_process_expr': '',
        },
    },
    'free_subject': {
        'type': 'CPS String Field',
        'data': {
            'default_expr': 'string:',
            'is_searchabletext': 1,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': [],
            'write_ignore_storage': 0,
            'write_process_expr': '',
        },
    },
    'how_important': {
        'type': 'CPS String Field',
        'data': {
            'default_expr': 'string:',
            'is_searchabletext': 1,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': [],
            'write_ignore_storage': 0,
            'write_process_expr': '',
        },
    },
    'all_pilots': {
        'type': 'CPS String List Field',
        'data': {
            'default_expr': 'string:',
            'is_searchabletext': 1,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': [],
            'write_ignore_storage': 0,
            'write_process_expr': '',
        },
    },
    'last_signature': {
        'type': 'CPS String Field',
        'data': {
            'default_expr': 'string:Directeur Général',
            'is_searchabletext': 1,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': [],
            'write_ignore_storage': 0,
            'write_process_expr': '',
        },
    },
    }

extended_metadata_schema = {
    'year_ref': {
        'type': 'CPS String Field',
        'data': {
            'default_expr': """string:""",
            'is_searchabletext': 0,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': (),
            'write_ignore_storage': 0,
            'write_process_expr': '',
            'submit_to_validate': 0,
        },
    },
    'value_ref': {
        'type': 'CPS String Field',
        'data': {
            'default_expr': """string:""",
            'is_searchabletext': 0,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': (),
            'write_ignore_storage': 0,
            'write_process_expr': '',
            'submit_to_validate': 0,
        },
    },
    'commission_ref': {
        'type': 'CPS String Field',
        'data': {
            'default_expr': """string:""",
            'is_searchabletext': 0,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': (),
            'write_ignore_storage': 0,
            'write_process_expr': '',
            'submit_to_validate': 0,
        },
    },
    'doctype_ref': {
        'type': 'CPS String Field',
        'data': {
            'default_expr': """string:""",
            'is_searchabletext': 0,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': (),
            'write_ignore_storage': 0,
            'write_process_expr': '',
            'submit_to_validate': 0,
        },
    },
    'DocumentType': {
        'type': 'CPS String Field',
        'data': {
            'default_expr': """string:""",
            'is_searchabletext': 1,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': (),
            'write_ignore_storage': 0,
            'write_process_expr': '',
            'submit_to_validate': 0,
        },
    },
    'Keywords': {
        'type': 'CPS String List Field',
        'data': {
            'default_expr': """python:''""",
            'is_searchabletext': True,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': False,
            'read_process_expr': '',
            'read_process_dependent_fields': (),
            'write_ignore_storage': False,
            'write_process_expr': '',
            'submit_to_validate': False,
        },
    },
    'Editor': {
        'type': 'CPS String Field',
        'data': {
            'default_expr': """string:""",
            'is_searchabletext': 1,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': (),
            'write_ignore_storage': 0,
            'write_process_expr': '',
            'submit_to_validate': 0,
        },
    },
    'Commission': {
        'type': 'CPS String List Field',
        'data': {
            'default_expr': """python:[]""",
            'is_searchabletext': 1,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': (),
            'write_ignore_storage': 0,
            'write_process_expr': '',
            'submit_to_validate': 0,
        },
    },
    'Demandeur': {
        'type': 'CPS String Field',
        'data': {
            'default_expr': """string:""",
            'is_searchabletext': 0,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': (),
            'write_ignore_storage': 0,
            'write_process_expr': '',
            'submit_to_validate': 0,
        },
    },
    'Reference': {
        'type': 'CPS String Field',
        'data': {
            'default_expr': """string:""",
            'is_searchabletext': 1,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': (),
            'write_ignore_storage': 0,
            'write_process_expr': '',
            'submit_to_validate': 0,
        },
    },
    'Creator': {
        'type': 'CPS String Field',
        'data': {
            'default_expr': """string:""",
            'is_searchabletext': 1,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': (),
            'write_ignore_storage': 1,
            'write_process_expr': '',
            'submit_to_validate': 0,
        },
    },
    'Warning': {
        'type': 'CPS String Field',
        'data': {
            'default_expr': """string:""",
            'is_searchabletext': 1,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': (),
            'write_ignore_storage': 0,
            'write_process_expr': '',
            'submit_to_validate': 0,
        },
    },
    'Rapporteur': {
        'type': 'CPS String Field',
        'data': {
            'default_expr': """string:""",
            'is_searchabletext': 0,
            'acl_read_permissions': '',
            'acl_read_roles': '',
            'acl_read_expr': '',
            'acl_write_permissions': '',
            'acl_write_roles': '',
            'acl_write_expr': '',
            'read_ignore_storage': 0,
            'read_process_expr': '',
            'read_process_dependent_fields': (),
            'write_ignore_storage': 0,
            'write_process_expr': '',
            'submit_to_validate': 0,
        },
    },
}



def getDocumentSchemas(portal=None):
    #all_shemas = portal.getDocumentSchemas(loadcustom=0)
    all_shemas = portal.getDocumentSchemas()
    metadata_schema = all_shemas['metadata']
    metadata_schema['Contributors']['data']['write_process_expr'] = 'python:portal.computeContributors(user, value, context)'
    metadata_schema.update(extended_metadata_schema)

    schemas = {}
    schemas['common'] = common_schema
    schemas['ooo_docbook_document'] = ooo_docbook_document_schema
    schemas['metadata'] = metadata_schema
    return schemas


ooo_docbook_document_layout = {
    'widgets': {
##         'Keywords': {
##             'type': 'Lines Widget',
##             'data': {
##                 'title': '',
##                 'fields': ('Keywords',),
##                 'is_required': False,
##                 'label': 'label_metadata_keywords',
##                 'label_edit': 'label_metadata_keywords',
##                 'description': '',
##                 'help': '',
##                 'is_i18n': True,
##                 'readonly_layout_modes': (),
##                 'hidden_layout_modes': (),
##                 'hidden_readonly_layout_modes': (),
##                 'hidden_empty': False,
##                 'hidden_if_expr': '',
##                 'css_class': '',
##                 'widget_mode_expr': '',
##                 'width': 40,
##                 'height': 5,
##                 'format_empty': "",
##             },
##         },
        'Source': {
            'type': 'String Widget',
            'data': {
                'fields': ['Source'],
                'hidden_layout_modes': ['view'],
                'is_i18n': 1,
                'label_edit': 'label_source',
                'label': '',
                'display_width': 30,
                'size_max': 80,
            },
        },
        'Rights': {
            'type': 'String Widget',
            'data': {
                'fields': ['Rights'],
                'hidden_layout_modes': ['view'],
                'is_i18n': 1,
                'label_edit': 'label_rights',
                'label': '',
                'display_width': 30,
                'size_max': 80,
            },
        },
        'file': {
            'type': 'AttachedFile Widget',
            'data': {
                'fields': ['file',
                           'file_text',
                           'file_html'],
                'is_i18n': 1,
                'label_edit': 'cpsdoc_News_attachedFile_label_edit',
                'label': 'cpsdoc_News_attachedFile_label',
                'hidden_empty': 1,
                'description': 'cpsdoc_News_attachedFile_description',
                'help': "Il n'est pas utile de remplir les champs ci-dessous, hormis le champ « Titre ». Ils seront renseignés directement lors du téléchargement de votre document OpenOffice.",
                'deletable': 1,
                'size_max': 20*1024*1024,
                'allowed_suffixes': ('.sxw',),
            },

        },
#        'archive_revision': {
#            'type': 'Method Widget',
#            'data': {
#                'fields': [],
#                'is_required': 0,
#                'label_edit': '',
#                'label': 'label_archive_revision',
#                'description': '',
#                'is_i18n': 1,
#                'hidden_layout_modes' : ['create', 'view'],
#                'render_method': 'widget_archive_revision_render',
#            },
#        },
    },
    'layout': {
        'style_prefix': 'layout_default_',
        'ncols': 2,
        'rows': [
##             [{'widget_id': 'Keywords'}, ],
            [{'widget_id': 'Source'},
             {'widget_id': 'Rights'},],
            [{'widget_id': 'file'}, ],
            [{'widget_id': 'archive_revision'}, ],
            ],
        },
    }



def getDocumentLayouts(portal=None):
    layouts = {}
    layouts['ooo_docbook_document'] = ooo_docbook_document_layout
    return layouts
